app_root/urls.py
from django.contrib import admin
from django.urls import path,include

from django.shortcuts import render

def index(request):
    return render(request, "index.html", {})

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    #-------------------------------------------------app_store
    path('app-store/', include('app_store.urls', namespace='as')),


]

app_store/urls.py
from django.urls import path, include
from . import views_supplier, views_material

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from .api import views as viewsApi

app_name = 'app_store'

#---------ROUTE WEb
urlpatternsWeb = [
    #------------------------------------------------------------Supplier
    path('supplier/delete/<int:pk>', views_supplier.SupplierDeleteView.as_view(), name='supplier-delete'),
    path('supplier/update/<int:pk>', views_supplier.SupplierUpdateView.as_view(), name='supplier-update'),
    path('supplier/create/', views_supplier.SupplierCreateView.as_view(),name='supplier-create'),
    path('supplier/', views_supplier.SupplierListView.as_view(), name='supplier-index'),
    #------------------------------------------------------------Material
    path('material/detail/<int:pk>', views_material.MaterialDetailView.as_view(), name='material-detail'),
    path('material/delete/<int:pk>', views_material.MaterialDeleteView.as_view(), name='material-delete'),
    path('material/update/<int:pk>', views_material.MaterialUpdateView.as_view(), name='material-update'),
    path('material/create/', views_material.MaterialCreateView.as_view(),name='material-create'),
    path('material/', views_material.MaterialListView.as_view(), name='material-index'),
]



@api_view(['GET'])
def api_store(request, format=None):
    return Response({
        'suppliers': reverse('as:api-supplier-list', request=request, format=format),
        'materials': reverse('as:api-material-list', request=request, format=format),
    })

#---------ROUTE API
urlpatternsApi = [
    # path('', views.index),
    path('api/', api_store,name='api-root'),
    # ----------------------------------------------------------------supplier
    path('api/supplier', viewsApi.SupplierList.as_view(), name='api-supplier-list'),
    path('api/supplier/<int:pk>/', viewsApi.SupplierDetail.as_view(),  name='api-supplier-detail'),
    # ----------------------------------------------------------------material
    path('api/material/', viewsApi.MaterialList.as_view(), name='api-material-list'),
    path('api/material/<int:pk>/', viewsApi.MaterialDetail.as_view(),  name='api-material-detail'),
]

urlpatterns = urlpatternsWeb + urlpatternsApi

app_store/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=20,default='',unique=True)

    def __str__(self):
        return "[{}] Supplier {}".format(self.id,self.name)
        # return "Supplier {}".format(self.name)

#------------------------------------------------------------------------------------------
class Material(models.Model):
    TYPE_CHOICES = (
        ('FABRIC', 'Fabric'),
        ('JEANS', 'Jeans'),
        ('COTTON', 'Cotton'),
    )
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE,related_name='materials')

    code = models.CharField(max_length=10,default='')
    name = models.CharField(max_length=50,default='')
    type = models.CharField(max_length=10,choices=TYPE_CHOICES, default='Cotton')
    buyPrice = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "[{}] Material {} | {}".format(self.id,self.name, self.supplier)
        # return "Material {} | {}".format(self.name, self.supplier)

app_store/api/views.py
from rest_framework import generics, permissions, renderers

from app_store import models
from . import serializers

#-----------------------------------------------------Supplier
class SupplierList(generics.ListCreateAPIView):
    queryset = models.Supplier.objects.all()
    serializer_class = serializers.SerializerModelSupplier


class SupplierDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Supplier.objects.all()
    serializer_class = serializers.SerializerModelSupplier


#-----------------------------------------------------Material
class MaterialList(generics.ListCreateAPIView):
    queryset = models.Material.objects.all()
    serializer_class = serializers.SerializerModelMaterial


class MaterialDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Material.objects.all()

    serializer_class = serializers.SerializerModelMaterial

app_store/views.py
from django.shortcuts import render

# Create your views here.

app_store/templates/app_store/material/create.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    {% comment %} <link rel="stylesheet" href="{% static 'backend_phm/css/style_form.css' %} "> {% endcomment %}
    <link rel="stylesheet" href="{% static 'vendor/select-picker/bootstrap-select.min.css' %}">

{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}
    <div class="container  ">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                    <a class="btn btn-secondary" href={% url 'as:material-index'  %}>
                    <i class='mdi mdi-keyboard-backspace'></i> Semua {{page_role}}
                  </a>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5 pt-3">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
      <br>
{% comment %} content {% endcomment %}
       <form method="POST" enctype="multipart/form-data">
         {% csrf_token %}

            {{form.as_p}}
         
         <br>
         <a class="btn btn-secondary" href="{% url 'as:material-index' %} ">Batal</a>
         <button type="submit" class="btn btn-success">submit</button>
       </form>

    </div>

{% endblock content %}


{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    {% comment %} <script src="{% static 'backend_phm/js/script.js' %}"></script> {% endcomment %}
    <script src="{% static 'vendor/select-picker/bootstrap-select.min.js' %}"></script>

    <script>
        (function($) {
        'use strict';
            $(function() {
                $( "#material" ).addClass('active');
                $( ".errorlist" ).addClass('alert alert-danger');

                //$('#id_nama').attr('readonly','readonly');
                
                $('#id_type').removeAttr('class','form-control');
                $('#id_type').attr('class','selectpicker');
                $('#id_type').attr('data-live-search','true');
                $('#id_type').attr('data-width','100%');
                $('#id_type').attr('title','--pilih--');
                $('#id_type').attr('required','required');
                //$('#id_type').attr('multiple','multiple');
                $('.selectpicker').selectpicker('refresh');
  
            });
        })(jQuery);
    </script>
{% endblock app_scripts %}

app_store/templates/app_store/material/detail.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    {% comment %} <link rel="stylesheet" href="{% static 'backend_phm/css/style.css' %} "> {% endcomment %}
    <style>
    .table-responsive {
        display: table;
    }
    </style>
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}
    <div class="container  ">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
          
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                    <a class="btn btn-secondary" href={% url 'as:material-index'  %}>
                    <i class='mdi mdi-keyboard-backspace'></i> Semua {{page_role}}
                  </a>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5 pt-3">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
    <br>

        <div class="card">
            <div class="card-header">
                {% comment %} <p><u> <a href="{{model.file_model.url}}" target='__blank'>Unduh model</a></u> </p> {% endcomment %}
            </div>
            <div class="card-body">
            <div class="table-responsive">
             <table border='0' style='font-size : 14px' class='table table-striped table-hover'>
                   <thead>
                    <tr>
                        <th width='18%'>Atribut</th>
                        <th width='3%' class='text-center'>|</th>
                        <th>Nilai</th>
                    </tr>                
                    </thead>
                    <tr>
                        <td>Kode</td>
                        <td width='5%' class='text-center'> : </td>
                        <td>{{material.code}}  </td>
                    </tr>
                    <tr>
                        <td>Supplier</td>
                        <td width='5%' class='text-center'> : </td>
                        <td>{{material.supplier.name}}  </td>
                    </tr>
                    <tr>
                        <td>Nama</td>
                        <td width='5%' class='text-center'> : </td>
                        <td>{{material.name}}  </td>
                    </tr>
                    <tr>
                        <td>Tipe</td>
                        <td width='5%' class='text-center'> : </td>
                        <td>{{material.type}}  </td>
                    </tr>
                    <tr>
                        <td>Harga Beli</td>
                        <td width='5%' class='text-center'> : </td>
                        <td>{{material.buyPrice}}  </td>
                    </tr>
                </table>
            </div>
            </div>
        </div>

    </div>

{% endblock content %}

{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    {% comment %} <script src="{% static 'backend_phm/js/script.js' %}"></script> {% endcomment %}
    <script>
        (function($) {
        'use strict';
            $(function() {
                $( "#material" ).addClass('active');

            });
        })(jQuery);
    </script>
{% endblock app_scripts %}

app_store/templates/app_store/material/index.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %} "> {% endcomment %}
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}

    <div class=" mr-3">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="ml-4 ml-xl-5 mt-3">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
              <div class="d-flex align-items-end flex-wrap">

                <div class="mr-4 mr-xl-4 ml-4 pt-3">

                    <a class="btn btn-outline-success btn-icon-text" href="{% url 'as:material-create' %}">
                      <i class='mdi mdi-hospital btn-icon-prepend'></i> Tambah {{page_role}}
                    </a>

                </div>

              </div>
            </div>
          </div>
        </div>
      <br>
{% comment %} content {% endcomment %}
              <div class="card">
                <div class="card-header alert-warning" >
                  {% comment %} <h6> <u> Perhatian </u>: field Nama bersifat "case sensitif" dan unik </h6> {% endcomment %}
                </div>
                <div class="card-body">
                  <div class="text-right filter-col-Type" id="filterCol_i" data-column="3" >
                    <label><p> filter TIPE : </p></label>
                    <select name="JobID" class="column_filter" id="filterCol_type">
                      <option>All</option>
                        {% for typeChoice in typeChoices %}
                          <option value="{{typeChoice.0}}">{{typeChoice.1}}</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="table-responsive">
                    <table id="datatable" class="table table-hover">
                      <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th >Kode</th>
                            <th >Supplier</th>
                            <th >Nama</th>
                            <th >Tipe</th>
                            <th >Harga Beli</th>
                            <th width="13%">Kelola</th>
                        </tr>
                      </thead> 
                      <tbody>
                            
                            {% for material in materials %}
                              <tr>
                                <td class='text-center'>{{forloop.counter}} </td>
                                <td> {{material.code}} </td>   
                                <td> {{material.supplier.name}} </td>   
                                <td> {{material.name}} </td>   
                                <td> {{material.type}} </td>   
                                <td> {{material.buyPrice}} </td>   

                                <td>
                                    <a class="btn btn-outline-primary btn-fw" href="{% url 'as:material-detail' material.id %}" title='detail {{material}} '><i class="mdi mdi-book-open-page-variant"></i></a>
                                    <a class="btn btn-outline-warning btn-fw" href="{% url 'as:material-update' material.id %}" title='edit {{material}}'><i class="mdi mdi-eyedropper"></i></a>
                                    <a id="delete-data" class="btn btn-outline-danger btn-fw" href="{% url 'as:material-delete' material.id %}" title='hapus {{material}}'><i class="mdi mdi-delete-forever"></i></a>
                                </td>
                              </tr>        
                            {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

    </div>
{% endblock content %}


{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    {% comment %} <script src="{% static 'buku/js/script.js' %}"></script> {% endcomment %}
    <script>
    (function($) {
        'use strict';
        $(function() {
            //active sidebar
            $("#material").addClass('active');
            //data table
            $('#datatable').DataTable({
                "aLengthMenu": [
                    [5, 10, 15, -1],
                    [5, 10, 15, "All"]
                ],
                "iDisplayLength": 10,
                "language": {
                    search: "search : "
                },
                searching: true, paging: true, info: true
            });
            //filter
            $('#filterCol_type').on('change', function () {
                //filterColumn( $(this).parents('div').attr('data-column') );
                let valType = $(this).val()
                console.log(valType)
                if (valType === 'All'){
                  console.log('cek')
                  $('#datatable').DataTable().columns('').search('').draw();
                }else{
                  $('#datatable').DataTable().column(4).search(valType).draw()
                }
            } );
            //flash message
            {% if messages %}
              {% for message in messages %}
                swal({
                  type: 'success',
                  title: 'Berhasil!',
                  text: '{{message}}',
                  timer: 2500
                });
              {% endfor %}
            {% endif %}

            // action add update

              // delete
              $('body').on('click', '#delete-data', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title'),
                      csrf_token = $("[name=csrfmiddlewaretoken]").val();
                  swal({
                      title: 'Apakah Anda Yakin ?',
                      text: 'ingin meng' + '"'+ title +'"',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Hapus',
                      cancelButtonText: 'Batal'
                  }).then((result) => {
                  if (result.value) {
                      $.ajax({
                          url: url,
                          type: "POST",
                          data: {
                              'csrfmiddlewaretoken': csrf_token
                          },
                          success: function (response) {
                              setTimeout(function () { location.reload();}, 2600);
                              swal({
                                  type: 'success',
                                  title: 'Success!',
                                  text: 'Data ' + '"'+ title +'"'+ ' berhasil dihapus!',
                                  timer: 2500

                              });
                          },
                          error: function (xhr) {
                              swal({
                                  type: 'error',
                                  title: 'Oops...',
                                  text: 'Something went wrong!'
                              });
                          }
                      });
                  }
                  });
              });



        });
    })(jQuery);
    </script>
{% endblock app_scripts %}

app_store/templates/app_store/supplier/create.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    {% comment %} <link rel="stylesheet" href="{% static 'backend_phm/css/style_form.css' %} "> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="{% static 'vendor/select-picker/bootstrap-select.min.css' %}"> {% endcomment %}

{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}
    <div class="container  ">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex align-items-end flex-wrap">
                <div class="mr-3 mr-xl-5 ml-4">
                    <a class="btn btn-secondary" href={% url 'as:supplier-index'  %}>
                    <i class='mdi mdi-keyboard-backspace'></i> Semua {{page_role}}
                  </a>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="mr-3 mr-xl-5 pt-3">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
            </div>
          </div>
        </div>
      <br>
{% comment %} content {% endcomment %}
       <form method="POST" enctype="multipart/form-data">
         {% csrf_token %}

            {{form.as_p}}
         
         <br>
         <a class="btn btn-secondary" href="{% url 'as:supplier-index' %} ">Batal</a>
         <button type="submit" class="btn btn-success">submit</button>
       </form>

    </div>

{% endblock content %}


{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    {% comment %} <script src="{% static 'backend_phm/js/script.js' %}"></script> {% endcomment %}
    {% comment %} <script src="{% static 'vendor/select-picker/bootstrap-select.min.js' %}"></script> {% endcomment %}

    <script>
        (function($) {
        'use strict';
            $(function() {
                $( "#supplier" ).addClass('active');
                $( ".errorlist" ).addClass('alert alert-danger');
            });
        })(jQuery);
    </script>
{% endblock app_scripts %}

app_store/templates/app_store/supplier/index.html
{% extends 'templates.html' %}
{% load static %}

{% comment %} CSS {% endcomment %}
{% block app_style %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %} "> {% endcomment %}
{% endblock app_style %}

{% comment %} CONTENT {% endcomment %}
{% block content_header %}
{% endblock content_header %}

{% block content %}

    <div class=" mr-3">
    {% comment %} header {% endcomment %}
        <div class="row">
          <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between flex-wrap">
              <div class="d-flex justify-content-between align-items-end flex-wrap">
                  <div class="ml-4 ml-xl-5 mt-3">
                    <h2>{{page_judul}}</h2>
                    <p class="mb-md-0">{{page_deskripsi}} </p>
                  </div>
              </div>
              <div class="d-flex align-items-end flex-wrap">

                <div class="mr-4 mr-xl-4 ml-4 pt-3">

                    <a class="btn btn-outline-success btn-icon-text" href="{% url 'as:supplier-create' %}">
                      <i class='mdi mdi-hospital btn-icon-prepend'></i> Tambah {{page_role}}
                    </a>

                </div>

              </div>
            </div>
          </div>
        </div>
      <br>
{% comment %} content {% endcomment %}
              <div class="card">
                <div class="card-header alert-warning" >
                  <h6> <u> Perhatian </u>: field Nama bersifat "case sensitif" dan unik </h6>

                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table id="datatable" class="table table-hover">
                      <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th >Nama</th>
                            <th width="13%">Kelola</th>
                        </tr>
                      </thead> 
                      <tbody>
                            
                            {% for supplier in suppliers %}
                              <tr>
                                <td class='text-center'>{{forloop.counter}} </td>
                                <td> {{supplier.name}} </td>   

                                <td>
                                    <a class="btn btn-outline-secondary btn-fw" href="#" disabled title='detail {{supplier}} '><i class="mdi mdi-book-open-page-variant"></i></a>
                                    {% comment %} <a class="btn btn-outline-primary btn-fw" href="{% url 'as:supplier-detail' supplier.id %}" title='detail {{supplier}} '><i class="mdi mdi-book-open-page-variant"></i></a> {% endcomment %}
                                    <a class="btn btn-outline-warning btn-fw" href="{% url 'as:supplier-update' supplier.id %}" title='edit {{supplier}}'><i class="mdi mdi-eyedropper"></i></a>
                                    <a id="delete-data" class="btn btn-outline-danger btn-fw" href="{% url 'as:supplier-delete' supplier.id %}" title='hapus {{supplier}}'><i class="mdi mdi-delete-forever"></i></a>
                                </td>
                              </tr>        
                            {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

    </div>
{% endblock content %}


{% comment %} JAVASCRIPTS {% endcomment %}
{% block app_scripts %}
    {% comment %} <script src="{% static 'buku/js/script.js' %}"></script> {% endcomment %}
    <script>
    (function($) {
        'use strict';
        $(function() {
            $("#supplier").addClass('active');
            
            $('#datatable').DataTable({
                "aLengthMenu": [
                    [5, 10, 15, -1],
                    [5, 10, 15, "All"]
                ],
                "iDisplayLength": 10,
                "language": {
                    search: "search : "
                },
                searching: true, paging: true, info: true
            });

            {% if messages %}
              {% for message in messages %}
                swal({
                  type: 'success',
                  title: 'Berhasil!',
                  text: '{{message}}',
                  timer: 2500
                });
              {% endfor %}
            {% endif %}

            // action add update

              // delete
              $('body').on('click', '#delete-data', function (event) {
                  event.preventDefault();
                  var me = $(this),
                      url = me.attr('href'),
                      title = me.attr('title'),
                      csrf_token = $("[name=csrfmiddlewaretoken]").val();
                  swal({
                      title: 'Apakah Anda Yakin ?',
                      text: 'ingin meng' + '"'+ title +'"',
                      type: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Hapus',
                      cancelButtonText: 'Batal'
                  }).then((result) => {
                  if (result.value) {
                      $.ajax({
                          url: url,
                          type: "POST",
                          data: {
                              'csrfmiddlewaretoken': csrf_token
                          },
                          success: function (response) {
                              setTimeout(function () { location.reload();}, 2600);
                              swal({
                                  type: 'success',
                                  title: 'Success!',
                                  text: 'Data ' + '"'+ title +'"'+ ' berhasil dihapus!',
                                  timer: 2500

                              });
                          },
                          error: function (xhr) {
                              swal({
                                  type: 'error',
                                  title: 'Oops...',
                                  text: 'Something went wrong!'
                              });
                          }
                      });
                  }
                  });
              });



        });
    })(jQuery);
    </script>
{% endblock app_scripts %}

templates/partials/_footer.html
        <footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            {% comment %} <span class="text-muted text-center text-sm-right d-block d-sm-inline-block">Copyright © 2018 <a href="https://www.urbanui.com/" target="_blank">Urbanui</a>. All rights reserved.</span> {% endcomment %}
            <span class="text-muted text-center text-sm-right d-block d-sm-inline-block">
            </span>
            <span class="text-muted float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
            Copyright © 2021
            
            | <a href="https://technext.github.io/majestic/index.html">MajecticTheme</a>
            </span>
          </div>
        </footer>

templates/partials/_sidebar.html
{% load static %}
    
     <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
            <li class="nav-item" id="home">
              {% comment %} <a class="nav-link" href="/"> {% endcomment %}
              <a class="nav-link" href="{% url 'index' %}">
                <i class="mdi mdi-home menu-icon"></i>
                <span class="menu-title">Home</span>
              </a>
            </li>
            <li class="nav-item" id="supplier">
              <a class="nav-link" href="{% url 'as:supplier-index' %}">
                <i class="mdi mdi-account-network  menu-icon"></i>
                <span class="menu-title"> Kelola Supplier</span>
              </a>
            </li>
            <li class="nav-item" id="material">
              <a class="nav-link" href="{% url 'as:material-index' %}">
                <i class="mdi mdi-clipboard-text  menu-icon"></i>
                <span class="menu-title"> Kelola Material</span>
              </a>
            </li>
            <li class="nav-item" id="material">
              <a class="nav-link" href="{% url 'as:api-root' %}">
                <i class="mdi mdi-fire  menu-icon"></i>
                <span class="menu-title"> API App Store</span>
              </a>
            </li>

{% comment %} ------ {% endcomment %}
        {% comment %} {% if user.is_authenticated %}
          {% if user.is_superuser == 1 %}
        <li class="nav-item  alert-warning">
            <a class="nav-link" href="#">
              <span class="menu-title"></span>
            </a>
          </li> 
                <li class="nav-item" id="access-control">
                  <a class="nav-link" href="{% url 'index' %}">
                    <i class="mdi mdi-account-network menu-icon"></i>
                    <span class="menu-title">Access Control</span>
                  </a>
                </li>
          {% endif %}
        {% endif %} {% endcomment %}
  
{% comment %} ------ {% endcomment %}


        </ul>
      </nav>

templates/partials/_styles.html
{% load static %}

  <link rel="stylesheet" href="{% static 'majestic-thema/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'majestic-thema/vendors/base/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <link rel="stylesheet" href="{% static 'majestic-thema/vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'majestic-thema/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- endinject -->